# Generated by Django 3.2.6 on 2021-11-05 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaname', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=15, null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('userpic', models.FileField(null=True, upload_to='')),
                ('idpic', models.FileField(null=True, upload_to='')),
                ('aboutme', models.CharField(max_length=300, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('regdate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=15, null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('userpic', models.FileField(null=True, upload_to='')),
                ('regdate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donationname', models.CharField(max_length=100, null=True)),
                ('donationpic', models.FileField(null=True, upload_to='')),
                ('collectionloc', models.CharField(max_length=300, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('status', models.CharField(max_length=30, null=True)),
                ('donationdate', models.DateField(null=True)),
                ('adminremark', models.CharField(max_length=200, null=True)),
                ('volunteerremark', models.CharField(max_length=200, null=True)),
                ('updationdate', models.DateField(null=True)),
                ('donationarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.donationarea')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.donor')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.volunteer')),
            ],
        ),
    ]
