# Generated by Django 3.2.6 on 2021-11-08 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donationarea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donation.donationarea'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='volunteer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donation.volunteer'),
        ),
    ]
