# Generated by Django 3.1.3 on 2023-08-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0006_donation_donation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_type',
            field=models.IntegerField(choices=[(1, 'Product'), (2, 'Fund')], default=1, null=True),
        ),
    ]
