# Generated by Django 3.1.3 on 2023-08-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0007_auto_20230801_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='amount',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
